### ISSUE TITLE
Are you open for contribution?

### ISSUE THREAD

**Issue by Padi-owasp** [akuskis/mod_authg_jwt#1]
Hi Artem
I sumbled over your MOD for JWT validation. It already does most of what I need. Are you open to me contributing the following feature:
- Instead of a fixed JWKS-URL we read the jku header and use this url to fetch the JWK to verify signature.
-- This means additinal config param "useJkuHeader"
-- and additinal param "trustedJwkHosts" (list of servers trusted to provide JWK)
-- potential param "trustedJwkDomains" (list of domains trusted to provide JWK - valuable in intranet situations where you have a company CA trusted to issue host certs)

Or do you prefer when I fork and add the functionality in a new project?
Regards

**Comment by akuskis** [comment]
Hi Padi,
Yes, it sounds reasonable. You are welcome to submit this PR.

**Comment by akuskis** [comment]
And I'm contributions friendly, so please feel free to submit you changes.

**Comment by akuskis** [comment]
Just checked sources... I think that it's also required to replace map of keys by unordered_map.

**Comment by Padi-owasp** [comment]
Thanks. Will keep that in mind - hopefully ;-)
Btw: What Dev-Setup worked best for you in this project! Any special consideration, or just "your regular  dev-env?

**Comment by akuskis** [comment]
GNU Linux was used as dev machine and for testing I've used Apache in container (got some sandbox in k8s which I was curios to have running with JWT filtering on Apache side, but simple Docker container also should be fine).
Maybe you have your environment, where this feature is required.

**Comment by Padi-owasp** [comment]
Hi Artem
Well, I create an updated version with jku support and have it on a local feature/jku branch.
Are you willing to provide me the rights to commit to your repository?
Or can I send you a git patch file to some place?

I've also updated documentation. But as my last C/C++ projects is 15 years back I guess there will be some memory issues. So feedback and improvements welcome.
Cheers
Padi

**Comment by akuskis** [comment]
Hi Padi,

You can fork this project, create branch and submit your changes as Pull Request.

**Comment by Padi-owasp** [comment]
Hi Artem
Not sure if you are aware: I've create a new Pull-Request and closed the old one. The new one contains fixes for your comments and additional functionality for RedHat, and RS512 support. Please review.

... and happy New Year!

**Comment by akuskis** [comment]
Happy New Year, Padi.
Sorry for delay. PR looks good! Thank you!

**Comment by Padi-owasp** [comment]
No worries.
And a big thank you very much. For all the initial work, your support and the merge. :-).
